
import java.text.NumberFormat;
import javax.swing.JOptionPane;
public class CarLoanInterface extends javax.swing.JFrame {
   private LoanOperation operation;
   private Client client;
   private int index;
    
    public CarLoanInterface() {
        initComponents();
        operation = new LoanOperation();
        index = -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblOrganization = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        tfLoanAmount = new javax.swing.JTextField();
        lblInterest = new javax.swing.JLabel();
        tfInterest = new javax.swing.JTextField();
        lblYears = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        lblMonthlyPayment = new javax.swing.JLabel();
        tfTotalLoanAmount = new javax.swing.JTextField();
        tfMonthlyPayment = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        rbPublicSector = new javax.swing.JRadioButton();
        rbPrivateSector = new javax.swing.JRadioButton();
        cbNoOfYears = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDisplayAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Client Name");

        lblOrganization.setText("Type of organization");

        lblAmount.setText("Loan Amount");

        lblInterest.setText("Interest/Profit Rate(%)");

        lblYears.setText("No. of Year(s)");

        lblTotalAmount.setText("Total Loan Amount");

        lblMonthlyPayment.setText("Monthly Payment");

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jLabel8.setText("A list of client names");

        rbPublicSector.setText("Public Sector");

        rbPrivateSector.setText("Private Sector");
        rbPrivateSector.setActionCommand("Private Sector");
        rbPrivateSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrivateSectorActionPerformed(evt);
            }
        });

        cbNoOfYears.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select numbere of year(s)", "1", "2", "3", "4", "5", "6", "7" }));

        btnCalculate.setText("Calculate Loan & Save");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setToolTipText("");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDisplayAll.setText("Display All");
        btnDisplayAll.setToolTipText("");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrganization)
                                    .addComponent(lblAmount)
                                    .addComponent(lblName)
                                    .addComponent(lblYears))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbPublicSector, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbPrivateSector, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfName)
                                    .addComponent(tfLoanAmount)
                                    .addComponent(tfInterest)
                                    .addComponent(tfTotalLoanAmount)
                                    .addComponent(tfMonthlyPayment)
                                    .addComponent(cbNoOfYears, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInterest)
                                    .addComponent(lblTotalAmount)
                                    .addComponent(lblMonthlyPayment))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btnReset)
                        .addGap(35, 35, 35)
                        .addComponent(btnDisplayAll)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrganization)
                            .addComponent(rbPublicSector)
                            .addComponent(rbPrivateSector))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAmount)
                            .addComponent(tfLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInterest)
                            .addComponent(tfInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYears)
                            .addComponent(cbNoOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAmount)
                            .addComponent(tfTotalLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMonthlyPayment)
                            .addComponent(tfMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDisplayAll)
                            .addComponent(btnReset)
                            .addComponent(btnCalculate))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPrivateSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrivateSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPrivateSectorActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        //Calculate loan amount
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        double loanAmount = Double.parseDouble(tfLoanAmount.getText());
        double interest = Double.parseDouble(tfInterest.getText());
        String noOfYearsText = (String)cbNoOfYears.getSelectedItem();
        int noOfYears = Integer.parseInt(noOfYearsText);
        double totalLoanAmount = operation.calculateLoanAmount(interest,loanAmount,noOfYears);
        String totalLoanAmountString = currency.format(totalLoanAmount);
        tfMonthlyPayment.setText(totalLoanAmountString);
        tfTotalLoanAmount.setText(totalLoanAmount + "");
        double monthlyPayment = operation.calculateMonthlyPayment(totalLoanAmount, noOfYears);
        String monthPaymentString = currency.format(monthlyPayment);
        tfMonthlyPayment.setText(monthPaymentString);

        //Save Record
        String name = tfName.getText();
        String typeOfOrganization = null;
        if (rbPublicSector.isSelected())
            typeOfOrganization = "Public Sector";
        if (rbPrivateSector.isSelected())
            typeOfOrganization = "Private Sector";        
        ta.setText(name + "\n" + typeOfOrganization + "\n" + loanAmount+ "\n" + interest
                          + "\n" + noOfYears + "\n" + totalLoanAmount+ "\n" + monthlyPayment);
        client = new Client(name, typeOfOrganization, loanAmount, interest, noOfYears, totalLoanAmount, monthlyPayment);
        index++;
        operation.saveClient(client, index);
        JOptionPane.showMessageDialog(this, "The record has been saved successfully into array of object");
       
        
        //Reset all the input field after record saved
        tfName.setText("");
        rbPublicSector.setSelected(false);
        rbPrivateSector.setSelected(false);
        tfLoanAmount.setText("");
        tfInterest.setText("");
        cbNoOfYears.setSelectedIndex(0);
        tfTotalLoanAmount.setText("");
        tfMonthlyPayment.setText("");
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       tfName.setText("");
        rbPublicSector.setSelected(false);
        rbPrivateSector.setSelected(false);
        tfLoanAmount.setText("");
        tfInterest.setText("");
        cbNoOfYears.setSelectedIndex(0);
        tfTotalLoanAmount.setText("");
        tfMonthlyPayment.setText("");
        ta.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        String allRecord = operation.displayAllClients();
        ta.setText(allRecord);
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarLoanInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarLoanInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarLoanInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarLoanInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarLoanInterface().setVisible(true);
            }
        });
    }//main method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbNoOfYears;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblInterest;
    private javax.swing.JLabel lblMonthlyPayment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblYears;
    private javax.swing.JRadioButton rbPrivateSector;
    private javax.swing.JRadioButton rbPublicSector;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tfInterest;
    private javax.swing.JTextField tfLoanAmount;
    private javax.swing.JTextField tfMonthlyPayment;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfTotalLoanAmount;
    // End of variables declaration//GEN-END:variables
}// class CarLoanInterface
