
import javax.swing.JOptionPane;

public class MainMenu extends javax.swing.JFrame {
    private Owner owner; 
    private BillOperation operation;
    
    public MainMenu() {
        initComponents();
        operation = new BillOperation();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbOwnerInformation = new javax.swing.JLabel();
        lbAccountNo = new javax.swing.JLabel();
        tfAccountNo = new javax.swing.JTextField();
        tfOwnerName = new javax.swing.JTextField();
        lbOwnerName = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        lbArrears = new javax.swing.JLabel();
        tfArrears = new javax.swing.JTextField();
        lbCurrentReading = new javax.swing.JLabel();
        lbPreviousReading = new javax.swing.JLabel();
        tfPreviousReading = new javax.swing.JTextField();
        lbBillDate = new javax.swing.JLabel();
        tfBillDate = new javax.swing.JTextField();
        tfCurrentReading = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbBillInformation = new javax.swing.JLabel();
        lbTotalUnit = new javax.swing.JLabel();
        tfTotalUnit = new javax.swing.JTextField();
        tfCurrentCharge = new javax.swing.JTextField();
        lbCurrentCharge = new javax.swing.JLabel();
        lbTotalBill = new javax.swing.JLabel();
        tfTotalBill = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbSearchAccountNumber = new javax.swing.JLabel();
        tfSearchAccountNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        lbBillInformation1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Electricity Billing System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbOwnerInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbOwnerInformation.setText("OWNER INFORMATION");

        lbAccountNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbAccountNo.setText("Account Number:");

        tfAccountNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfAccountNo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAccountNoActionPerformed(evt);
            }
        });

        tfOwnerName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfOwnerName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOwnerNameActionPerformed(evt);
            }
        });

        lbOwnerName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbOwnerName.setText("Name:");

        lbAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbAddress.setText("Address:");

        tfAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfAddress.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        lbArrears.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbArrears.setText("Arrears (RM):");

        tfArrears.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfArrears.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfArrears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArrearsActionPerformed(evt);
            }
        });

        lbCurrentReading.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbCurrentReading.setText("Current Reading:");

        lbPreviousReading.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbPreviousReading.setText("Previous Reading:");

        tfPreviousReading.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfPreviousReading.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfPreviousReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPreviousReadingActionPerformed(evt);
            }
        });

        lbBillDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbBillDate.setText("Bill Date:");

        tfBillDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfBillDate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfBillDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBillDateActionPerformed(evt);
            }
        });

        tfCurrentReading.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfCurrentReading.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfCurrentReading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCurrentReadingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAccountNo)
                            .addComponent(lbAddress)
                            .addComponent(lbBillDate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbArrears)
                                    .addComponent(lbCurrentReading)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lbOwnerName)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(tfOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfArrears, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCurrentReading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lbOwnerInformation)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbPreviousReading)
                        .addGap(18, 18, 18)
                        .addComponent(tfPreviousReading, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOwnerInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAccountNo)
                    .addComponent(tfAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbOwnerName)
                    .addComponent(tfOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbArrears))
                            .addComponent(lbAddress)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfArrears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCurrentReading)
                        .addComponent(tfCurrentReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfBillDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBillDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPreviousReading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPreviousReading))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbTitle.setText("ELECTRICITY BILLING SYSTEM");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbBillInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbBillInformation.setText("BILL INFORMATION");

        lbTotalUnit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbTotalUnit.setText("Total Unit: (kWH):");

        tfTotalUnit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfTotalUnit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfTotalUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalUnitActionPerformed(evt);
            }
        });

        tfCurrentCharge.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfCurrentCharge.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfCurrentCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCurrentChargeActionPerformed(evt);
            }
        });

        lbCurrentCharge.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbCurrentCharge.setText("Current Charge (RM):");

        lbTotalBill.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbTotalBill.setText("Total Bill (RM):");

        tfTotalBill.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfTotalBill.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfTotalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalBillActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSave.setText("Calculate & Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbBillInformation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbTotalUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCurrentCharge)
                        .addGap(18, 18, 18)
                        .addComponent(tfCurrentCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTotalBill)
                        .addGap(18, 18, 18)
                        .addComponent(tfTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnSave)
                .addGap(149, 149, 149)
                .addComponent(btnDisplay)
                .addGap(141, 141, 141)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBillInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalUnit)
                    .addComponent(tfTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCurrentCharge)
                    .addComponent(tfCurrentCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalBill))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDisplay)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbSearchAccountNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbSearchAccountNumber.setText("Search Account Number:");

        tfSearchAccountNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tfSearchAccountNo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tfSearchAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchAccountNoActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbSearchAccountNumber)
                        .addGap(18, 18, 18)
                        .addComponent(tfSearchAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearchAccountNumber)
                    .addComponent(tfSearchAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        lbBillInformation1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbBillInformation1.setText("Record Display");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbBillInformation1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBillInformation1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTotalUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalUnitActionPerformed

    private void tfCurrentChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCurrentChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCurrentChargeActionPerformed

    private void tfTotalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalBillActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String output = "";
        int searchAccountNo = Integer.parseInt(tfSearchAccountNo.getText());
        Owner owr = operation.searchRecord(searchAccountNo);
        
        if(owr == null)
            ta.setText("Sorry, the record does not exist");
        else{
            JOptionPane.showMessageDialog(this, "The record of this account " + searchAccountNo + " is found.");
            tfSearchAccountNo.setText("");
            output = "Account No: " + owr.getAccountNo() + "\nBill Date: " + owr.getBillDate() + "\nName: " + owr.getOwnerName() + "\nAddress: " + owr.getOwnerAddress() + "\nArrears: RM" + owr.getArrears()
                    + "\nPrevious Meter Reading: " + owr.getPreviousMeterReading()+ "\nCurrent Meter Reading: " + owr.getCurrentMeterReading() + "\nTotal Unit (kWh): "
                    + owr.getTotalUnit() + "\nCurrent Charge (RM): " + owr.getCurrentCharge() + "\nTotal Bill (RM): " + owr.getTotalBill();
            ta.setText(output);
            tfAccountNo.setText(owr.getAccountNo());
            tfOwnerName.setText(owr.getOwnerName());
            tfAddress.setText(owr.getOwnerAddress());
            tfArrears.setText(owr.getArrears());
            tfBillDate.setText(owr.getBillDate());
            tfPreviousReading.setText(owr.getPreviousMeterReading());
            tfCurrentReading.setText(owr.getCurrentMeterReading());
            tfTotalUnit.setText(owr.getTotalUnit());
            tfCurrentCharge.setText(owr.getCurrentCharge());
            tfTotalBill.setText(owr.getTotalBill());           
        }//else
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tfSearchAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchAccountNoActionPerformed
        
    }//GEN-LAST:event_tfSearchAccountNoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfAccountNo.setText("");
        tfOwnerName.setText("");
        tfAddress.setText("");
        tfArrears.setText("");
        tfBillDate.setText("");
        tfPreviousReading.setText("");
        tfCurrentReading.setText("");
        tfTotalUnit.setText("");
        tfCurrentCharge.setText("");
        tfTotalBill.setText("");
        tfSearchAccountNo.setText("");
        ta.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Boolean status = false;
        String accountNo = tfAccountNo.getText();
        String billDate = tfBillDate.getText();
        String ownerName = tfOwnerName.getText();
        String ownerAddress = tfAddress.getText();
        double arrears = Double.parseDouble(tfArrears.getText()); 
        int previousMeterReading = 0;
        int currentMeterReading = 0;       
         try{
             if(tfPreviousReading.getText().length() == 0){
                 JOptionPane.showMessageDialog(null, "Please enter previous meter reading");
                 status = false;   
             }
             else{ 
                 previousMeterReading = Integer.parseInt(tfPreviousReading.getText());
                 status = true;
        } 
         }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Invalid Previous Meter Reading", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
          try{
             if(tfCurrentReading.getText().length() == 0){
                 JOptionPane.showMessageDialog(null, "Please enter current meter reading");
                 status = false;   
             }
             else{ 
                 currentMeterReading = Integer.parseInt(tfCurrentReading.getText());
                 status = true;
        } 
         }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Invalid Current Meter Reading", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        if(status == true){  
        int totalUnit = operation.calculateTotalUnit(currentMeterReading, previousMeterReading);
        tfTotalUnit.setText(Integer.toString(totalUnit));
        double currentCharge = operation.calculateCurrentCharge(totalUnit);
        tfCurrentCharge. setText(Double.toString(currentCharge));
        
        double totalBill = operation.calculatTotalBill(currentCharge, arrears);
        String arrearsString = Double.toString(arrears);
        String previousMeterReadingString = Integer.toString(previousMeterReading);
        String currentMeterReadingString = Integer.toString(currentMeterReading);
        String currentChargeString = Double.toString(currentCharge);
        String totalUnitString = Double.toString(totalUnit);
        String totalBillString = Double.toString(totalBill);
        tfTotalBill. setText(Double.toString(totalBill));
       
        ta.setText("Account No: " + accountNo + "\nBill Date: " + billDate + "\nName: " + ownerName + "\nAddress: " + ownerAddress + "\nArrears: RM" + arrears
                   + "\nPrevious Meter Reading: " + previousMeterReading + "\nCurrent Meter Reading: " + currentMeterReading + "\nTotal Unit (kWh): " 
                   + totalUnit + "\nCurrent Charge (RM): " + currentCharge + "\nTotal Bill (RM): " + totalBill);
        
        owner = new Owner(accountNo, billDate, ownerName, ownerAddress, arrearsString, previousMeterReadingString, currentMeterReadingString, totalUnitString, currentChargeString,totalBillString);
        operation.addRecord(owner);
        JOptionPane.showMessageDialog(this, "The record has been saved successfully");
       
        tfAccountNo.setText("");
        tfOwnerName.setText("");
        tfAddress.setText("");
        tfArrears.setText("");
        tfBillDate.setText("");
        tfPreviousReading.setText("");
        tfCurrentReading.setText("");
        tfTotalUnit.setText("");
        tfCurrentCharge.setText("");
        tfTotalBill.setText("");
        tfSearchAccountNo.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed
  }
    private void tfBillDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBillDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBillDateActionPerformed

    private void tfPreviousReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPreviousReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPreviousReadingActionPerformed

    private void tfArrearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArrearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArrearsActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void tfOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOwnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOwnerNameActionPerformed

    private void tfAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAccountNoActionPerformed

    private void tfCurrentReadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCurrentReadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCurrentReadingActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
         String output = operation.displayAllRecord();
         ta.setText(output);                         
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int accountNo = Integer.parseInt(tfAccountNo.getText());
        String billDate = tfBillDate.getText();
        String ownerName = tfOwnerName.getText();
        String ownerAddress = tfAddress.getText();
        double arrears = Double.parseDouble(tfArrears.getText());
        int previousMeterReading = Integer.parseInt(tfPreviousReading.getText());
        int currentMeterReading = Integer.parseInt(tfCurrentReading.getText());
        int totalUnit = Integer.parseInt(tfTotalUnit.getText());
        double currentCharge = Double.parseDouble(tfCurrentCharge.getText());
        double totalBill = Double.parseDouble(tfTotalBill.getText());
       
        ta.setText("Account No: " + accountNo + "\nBill Date: " + billDate + "\nName: " + ownerName + "\nAddress: " + ownerAddress + "\nArrears: RM" + arrears
                   + "\nPrevious Meter Reading: " + previousMeterReading + "\nCurrent Meter Reading: " + currentMeterReading + "\nTotal Unit (kWh): " 
                   + totalUnit + "\nCurrent Charge (RM): " + currentCharge + "\nTotal Bill: " + totalBill);
        operation.updateRecord(owner);
        JOptionPane.showMessageDialog(this, "The record of this account " + accountNo + " is edited successfully.");
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int searchAccountNo = Integer.parseInt(tfAccountNo.getText());
        operation.deleteRecord(searchAccountNo);
        JOptionPane.showMessageDialog(this, "The record of this account " + searchAccountNo + " is deleted successfully.");
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAccountNo;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbArrears;
    private javax.swing.JLabel lbBillDate;
    private javax.swing.JLabel lbBillInformation;
    private javax.swing.JLabel lbBillInformation1;
    private javax.swing.JLabel lbCurrentCharge;
    private javax.swing.JLabel lbCurrentReading;
    private javax.swing.JLabel lbOwnerInformation;
    private javax.swing.JLabel lbOwnerName;
    private javax.swing.JLabel lbPreviousReading;
    private javax.swing.JLabel lbSearchAccountNumber;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTotalBill;
    private javax.swing.JLabel lbTotalUnit;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tfAccountNo;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfArrears;
    private javax.swing.JTextField tfBillDate;
    private javax.swing.JTextField tfCurrentCharge;
    private javax.swing.JTextField tfCurrentReading;
    private javax.swing.JTextField tfOwnerName;
    private javax.swing.JTextField tfPreviousReading;
    private javax.swing.JTextField tfSearchAccountNo;
    private javax.swing.JTextField tfTotalBill;
    private javax.swing.JTextField tfTotalUnit;
    // End of variables declaration//GEN-END:variables
}
